<?php

namespace ActiviteBundle\Repository;

/**
 * matieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matieresRepository extends \Doctrine\ORM\EntityRepository
{

}
