<?php

namespace ActiviteBundle\Repository;

/**
 * moniteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class moniteurRepository extends \Doctrine\ORM\EntityRepository
{
}
