<?php

namespace ActiviteBundle\Repository;

/**
 * parascolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parascolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
