<?php

namespace AbirBundle\Repository;

/**
 * clubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clubRepository extends \Doctrine\ORM\EntityRepository
{
}
