user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
user_admin:
    path:     /access/admin
    defaults: { _controller: UserBundle:Default:admin }
user_parent:
    path:     /access/parent
    defaults: { _controller: UserBundle:Default:parent }
user_animateur:
    path:     /access/animateur
    defaults: { _controller: UserBundle:Default:animateur }
user_chef:
    path:     /access/chef
    defaults: { _controller: UserBundle:Default:chef }
user_moniteur:
    path:     /access/moniteur
    defaults: { _controller: UserBundle:Default:moniteur }
home:
    path:     /home
    defaults: { _controller: UserBundle:Default:home }
