evenement_index:
    path:     /
    defaults: { _controller: "AbirBundle:evenement:index" }
    methods:  GET

evenement_show:
    path:     /{id}/show
    defaults: { _controller: "AbirBundle:evenement:show" }
    methods:  GET

evenement_new:
    path:     /new
    defaults: { _controller: "AbirBundle:evenement:new" }
    methods:  [GET, POST]

evenement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AbirBundle:evenement:edit" }
    methods:  [GET, POST]

evenement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AbirBundle:evenement:delete" }
    methods:  DELETE
