<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBceyxe5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBceyxe5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBceyxe5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBceyxe5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBceyxe5\appDevDebugProjectContainer([
    'container.build_hash' => 'Bceyxe5',
    'container.build_id' => 'd05c3025',
    'container.build_time' => 1581468376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBceyxe5');
